baseURL:  https://darktable-org.github.io/dtdocs/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: darktable user manual
    label: English
    weight: 1
  fr:
    title: darktable user manual
    label: Français
    weight: 2
  de:
    title: darktable user manual
    label: German
    weight: 4
  eo:
    title: darktable user manual
    label: Esperanto
    weight: 5
  es:
    title: darktable user manual
    label: Español
    weight: 6
  gl:
    title: darktable user manual
    label: Galician
    weight: 7
  it:
    title: darktable user manual
    label: Italian
    weight: 8
  pl:
    title: darktable user manual
    label: Polish
    weight: 9
  pt_br:
    title: manual do usuário darktable
    label: Português
    weight: 10
  uk:
    title: darktable user manual
    label: Ukrainian
    weight: 11
  nl:
    title: darktable user manual
    label: Dutch
    weight: 12
theme:
  - hugo-darktable-docs-pdf-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    renderer:
      unsafe: true
ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
