baseURL:  https://docs.darktable.org/usermanual/5.8/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: darktable 5.8 user manual
    languageName: English
  fr:
    title: darktable 5.8 user manual
    languageName: Français
  de:
    title: darktable 5.8 user manual
    languageName: German
  eo:
    title: darktable 5.8 user manual
    languageName: Esperanto
  es:
    title: darktable 5.8 user manual
    languageName: Español
  gl:
    title: darktable 5.8 user manual
    languageName: Galician
  it:
    title: darktable 5.8 user manual
    languageName: Italian
  pl:
    title: darktable 5.8 user manual
    languageName: Polish
  pt_br:
    title: manual do usuário darktable 5.8
    languageName: Português
  uk:
    title: darktable 5.8 user manual
    languageName: Ukrainian
  nl:
    title: darktable 5.8 user manual
    languageName: Dutch
  lo:
    title: darktable 5.8 user manual
    languageName: Lao
theme:
  - hugo-darktable-docs-theme
markup:
  highlight:
    style: algol_nu
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
outputs:
  home:
    - HTML
    - RSS
    - JSON
module:
  mounts:
    - source: ./themes//hugo-darktable-docs-theme/assets/node_modules/fork-awesome/fonts
      target: static/fonts
ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
