baseURL:
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: darktable user manual
    languageName: English
  fr:
    title: darktable user manual
    languageName: Français
  de:
    title: darktable user manual
    languageName: German
  eo:
    title: darktable user manual
    languageName: Esperanto
  es:
    title: darktable user manual
    languageName: Español
  gl:
    title: darktable user manual
    languageName: Galician
  it:
    title: darktable user manual
    languageName: Italian
  pl:
    title: darktable user manual
    languageName: Polish
  pt_br:
    title: manual do usuário darktable
    languageName: Português
  uk:
    title: darktable user manual
    languageName: Ukrainian
  nl:
    title: darktable user manual
    languageName: Dutch
  lo:
    title: darktable user manual
    languageName: Lao
theme:
  - hugo-darktable-docs-epub-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    extensions:
      typographer: false
    renderer:
      unsafe: true
      xHTML: true

disableKinds:
  - sitemap
  - taxonomy
  - term

uglyURLs: true
relativeURLs: true

mediaTypes:
  application/xhtml+xml:
    suffixes:
      - xhtml
  application/opf+xml:
    suffixes:
      - opf
  application/x-dtbncx+xml:
    suffixes:
      - ncx

outputFormats:
  XHTML:
    mediaType: application/xhtml+xml
    isHTML: true
    permalinkable: true
    baseName: toc
  OPF:
    mediaType: application/opf+xml
    isHTML: true
    permalinkable: true
    baseName: content
  NCX:
    mediaType: application/x-dtbncx+xml
    isHTML: true
    permalinkable: true
    baseName: toc

outputs:
  page:
    - HTML
  home:
    - OPF
    - NCX
    - HTML
    - XHTML
  section:
    - HTML

params:
  description: The user manual for darktable
  creator: darktable
  author: darktable
  publisher: darktable
ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
