baseURL:  https://darktable-org.github.io/dtdocs/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: darktable user manual
    languageName: English
  fr:
    title: darktable user manual
    languageName: Français
  de:
    title: darktable user manual
    languageName: German
  eo:
    title: darktable user manual
    languageName: Esperanto
  es:
    title: darktable user manual
    languageName: Español
  gl:
    title: darktable user manual
    languageName: Galician
  it:
    title: darktable user manual
    languageName: Italian
  pl:
    title: darktable user manual
    languageName: Polish
  pt_br:
    title: manual do usuário darktable
    languageName: Português
  uk:
    title: darktable user manual
    languageName: Ukrainian
  nl:
    title: darktable user manual
    languageName: Dutch
  lo:
    title: darktable user manual
    languageName: Lao
theme:
  - hugo-darktable-docs-pdf-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    renderer:
      unsafe: true
ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
